# Generated by Django 4.1.4 on 2023-01-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Брэнд', 'verbose_name_plural': 'Брэнды'},
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Верх', (('Худи', 'Худи'), ('Бомбер', 'Бомбер'))), ('Низ', (('Штаны', 'Штаны'),)), ('Обувь', (('Кроссы', 'Кроссы'), ('Туфли', 'Туфли'))), (None, 'Не определено')], default=None, max_length=25),
        ),
    ]
